### ISSUE TITLE
JIRA base url issue

### ISSUE THREAD

**Issue by bkak** [cptactionhank/docker-atlassian-jira#20]
Hi,

I get this error : 
     `Dashboard Diagnostics: Mismatched URL Hostname
JIRA is reporting that it is running on the hostname '172.31.11.210', which does not match the hostname used to run these diagnostics, 'my-host-name.com'. This is known to cause JIRA to construct URLs using the incorrect hostname, which will result in errors in the dashboard, among other issues.
The most common cause of this is the use of a reverse-proxy HTTP server (often Apache or IIS) in front of the application server running JIRA. While this configuration is supported, some additional setup might be necessary in order to ensure that JIRA detects the correct hostname.
The following articles describe the issue and the steps you should take to ensure that your web server and app server are configured correctly:
Gadgets do not display correctly after upgrade to JIRA 4.0
Integrating JIRA with Apache
Integrating JIRA with Apache using SSL
If you believe this diagnosis is in error, or you have any other questions, please contact Atlassian Support.`

I have JIRA behind Nginx proxy. So to fix this I updated the baseURL to : 'my-host-name.com'.
Some of the things got fixed, like creating new issue etc. But the dashboard does not show activity stream, and I get the above mentioned message after changing the baseURL also.

In the documentation it says we need to update server.xml file with this : 

<Connector acceptCount="100" connectionTimeout="20000" disableUploadTimeout="true" enableLookups="false" maxHttpHeaderSize="8192" maxThreads="150" minSpareThreads="25" port="8080" protocol="HTTP/1.1" redirectPort="8443" useBodyEncodingForURI="true" 
            proxyName="jira.atlassian.com" proxyPort="80"/> 

I tried finding server.xml like so: 

docker exec -it jira-docker /bin/bash 
Entered JIRA docker, but could not find server.xml file to make changes. 

How can we update the baseURL or fix this error?

**Comment by cptactionhank** [comment]
Hi @bkak and sorry for the long delay. You will need to restart your container after editing the `server.xml` file, however this file will not persist if you do not mount the installation directory by creating the container with the flag `--volume /opt/atlassian/jira`.

I am working on a easier and better way to get around proxy configuration, hoping it will be finished this weekend.

**Comment by cptactionhank** [comment]
Here is a working example using a `docker-compose.yml` to run a JIRA container behind a NGINX proxy server.

```yaml
jira:
  image: cptactionhank/atlassian-jira:latest
  environment:
    - "X_PROXY_NAME=docker"
    - "X_PROXY_PORT=80"
    - "X_PROXY_SCHEME=http"
    - "X_PATH=/jira"
  ports:
    - "1234:8080"

nginx:
  image: blacklabelops/nginx
  environment:
    - "SERVER1REVERSE_PROXY_LOCATION1=/"
    - "SERVER1REVERSE_PROXY_PASS1=http://jira:8080"
  links:
    - "jira:jira"
  ports:
   - "80:8080"
```
