### ISSUE TITLE
keeps restarting

### ISSUE THREAD

**Issue by sarkistlt** [cptactionhank/docker-atlassian-jira#40]
Using basic config to run 

```
version: '3'

services:
  app:
    restart: always
    image: cptactionhank/atlassian-jira:latest
    ports:
      - 9090:8080
    volumes:
      - ./docker/server.xml:/var/atlassian/jira/conf
```

It takes a while to open setup window, then it start restarting container `exited with code 137`, how can I make it work?
