### ISSUE TITLE
Cannot mount volumes properly using docker-compose

### ISSUE THREAD

**Issue by bishoybt** [cptactionhank/docker-atlassian-jira#56]
I am trying to start JIRA container using compose as following:

```
version: '3'

services:
  jira:
    image: cptactionhank/atlassian-jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    volumes:
      - ./installation:/opt/atlassian/jira
      - ./home:/var/atlassian/jira
    networks:
      - jira_net
```

when I run `docker-compose up -d` and then `docker ps --all`, it reports that jira has exited. Here is the logs:

```
stat: cannot stat '/opt/atlassian/jira/conf/server.xml': No such file or directory
/docker-entrypoint.sh: line 6: [: : integer expression expected
/docker-entrypoint.sh: line 21: /opt/atlassian/jira/bin/catalina.sh: No such file or directory
```

Which suggests that the JIRA install folder is not filled with files because I've mounted them as volumes.
